# Program to illustrate various mathematics functions
#functions include trigo, logarithms , squareroot, radian , tangential etc.
import math
x=float(input("Enter the value on which you want to perform various mathematical functions: "))
print()
print("Use of ceil() : Returns the smallest integer greater than or equal to x")
print(math.ceil(x))
print()
print("Use of floor() : Returns the largest integer less than or equal to x")
print(math.floor(x))
print()
print("Use of fabs() : Returns the absolute value of x")
print(math.fabs(x))
print()
print("Use of exp() : Returns the value of expression e**x")
print(math.exp(x))
print()
print("Use of log() : Returns the log(x) to the base b")
b=int(input("Enter the base"))
print("log(x,b) :",math.log(x,b))
print()
print("Useof pow(x,y) : Returns x raised to power y")
y=int(input("Enter the power of x"))
print("pow(x,y) :",math.pow(x,y))
print()
print("Use of sqrt() : Returns the square root of x")
print("sqrt(x) :",math.sqrt(x))
print()

print("cos(x) : Returns the cosine of x in radians")
x1=int(input("Enter the value whose cosine is to be found"))
print("cos(x) :",math.cos(x1))
print()
print("sin(x) : Returns the sine of x in radians")
x2=int(input("Enter the value whose sine is to be found"))
print("sin(x) :",math.sin(x2))
print()
print("tan(x) : Returns the tangent of x in radians")
x3=int(input("Enter the value whose tangent is to be found"))
print("tan(x) :",math.tan(x3))
print()
print("acos(x) : Returns the inverse cosine of x in radians")
x4=float(input("Enter the value whose inverse cosine is to be found"))
print("acos(x) :",math.acos(x4))
print()
print("asin(x) : Returns the inverse sine of x in radians")
x5=float(input("Enter the value whose inverse sine is to be found"))
print("asin(x) :",math.asin(x5))
print()
print("atan(x) : Returns the inverse tangent of x in radians")
x5=float(input("Enter the value whose inverse tangent is to be found"))
print("atan(x) :",math.atan(x5))
print()
print("degrees(x) : Returns a value in degrees equivalent of input value in x(in radians)")
x=float(input("Enter a value in radian"))
print("degrees(x) :",math.degrees(x))
print()
print("radians(x) : Returns a value in radian equivalent of input value(in degrees)")
x=float(input("Enter a value in degree"))
print("radians(x) :",math.radians(x))
      




